// WoW Retail Realm Data - sourced from official Blizzard realm status pages
// NA: https://worldofwarcraft.blizzard.com/en-us/game/status/us
// EU: https://worldofwarcraft.blizzard.com/en-gb/game/status/eu
// Last updated: 2026-03-03

export interface Realm {
  name: string;
  slug: string;
  region: "EU" | "NA";
}

// ─── NA (Americas & Oceania) Realms ─────────────────────────────────────────
export const NA_REALMS: Realm[] = [
  { name: "Aegwynn", slug: "aegwynn", region: "NA" },
  { name: "Aerie Peak", slug: "aerie-peak", region: "NA" },
  { name: "Agamaggan", slug: "agamaggan", region: "NA" },
  { name: "Aggramar", slug: "aggramar", region: "NA" },
  { name: "Akama", slug: "akama", region: "NA" },
  { name: "Alexstrasza", slug: "alexstrasza", region: "NA" },
  { name: "Alleria", slug: "alleria", region: "NA" },
  { name: "Altar of Storms", slug: "altar-of-storms", region: "NA" },
  { name: "Alterac Mountains", slug: "alterac-mountains", region: "NA" },
  { name: "Aman'Thul", slug: "amanthul", region: "NA" },
  { name: "Andorhal", slug: "andorhal", region: "NA" },
  { name: "Anetheron", slug: "anetheron", region: "NA" },
  { name: "Antonidas", slug: "antonidas", region: "NA" },
  { name: "Anub'arak", slug: "anubarak", region: "NA" },
  { name: "Anvilmar", slug: "anvilmar", region: "NA" },
  { name: "Arathor", slug: "arathor", region: "NA" },
  { name: "Archimonde", slug: "archimonde", region: "NA" },
  { name: "Area 52", slug: "area-52", region: "NA" },
  { name: "Argent Dawn", slug: "argent-dawn", region: "NA" },
  { name: "Arthas", slug: "arthas", region: "NA" },
  { name: "Arygos", slug: "arygos", region: "NA" },
  { name: "Auchindoun", slug: "auchindoun", region: "NA" },
  { name: "Azgalor", slug: "azgalor", region: "NA" },
  { name: "Azjol-Nerub", slug: "azjol-nerub", region: "NA" },
  { name: "Azralon", slug: "azralon", region: "NA" },
  { name: "Azshara", slug: "azshara", region: "NA" },
  { name: "Azuremyst", slug: "azuremyst", region: "NA" },
  { name: "Baelgun", slug: "baelgun", region: "NA" },
  { name: "Balnazzar", slug: "balnazzar", region: "NA" },
  { name: "Barthilas", slug: "barthilas", region: "NA" },
  { name: "Black Dragonflight", slug: "black-dragonflight", region: "NA" },
  { name: "Blackhand", slug: "blackhand", region: "NA" },
  { name: "Blackrock", slug: "blackrock", region: "NA" },
  { name: "Blackwater Raiders", slug: "blackwater-raiders", region: "NA" },
  { name: "Blackwing Lair", slug: "blackwing-lair", region: "NA" },
  { name: "Blade's Edge", slug: "blades-edge", region: "NA" },
  { name: "Bladefist", slug: "bladefist", region: "NA" },
  { name: "Bleeding Hollow", slug: "bleeding-hollow", region: "NA" },
  { name: "Blood Furnace", slug: "blood-furnace", region: "NA" },
  { name: "Bloodhoof", slug: "bloodhoof", region: "NA" },
  { name: "Bloodscalp", slug: "bloodscalp", region: "NA" },
  { name: "Bonechewer", slug: "bonechewer", region: "NA" },
  { name: "Borean Tundra", slug: "borean-tundra", region: "NA" },
  { name: "Boulderfist", slug: "boulderfist", region: "NA" },
  { name: "Bronzebeard", slug: "bronzebeard", region: "NA" },
  { name: "Burning Blade", slug: "burning-blade", region: "NA" },
  { name: "Burning Legion", slug: "burning-legion", region: "NA" },
  { name: "Caelestrasz", slug: "caelestrasz", region: "NA" },
  { name: "Cairne", slug: "cairne", region: "NA" },
  { name: "Cenarion Circle", slug: "cenarion-circle", region: "NA" },
  { name: "Cenarius", slug: "cenarius", region: "NA" },
  { name: "Cho'gall", slug: "chogall", region: "NA" },
  { name: "Chromaggus", slug: "chromaggus", region: "NA" },
  { name: "Coilfang", slug: "coilfang", region: "NA" },
  { name: "Crushridge", slug: "crushridge", region: "NA" },
  { name: "Daggerspine", slug: "daggerspine", region: "NA" },
  { name: "Dalaran", slug: "dalaran", region: "NA" },
  { name: "Dalvengyr", slug: "dalvengyr", region: "NA" },
  { name: "Dark Iron", slug: "dark-iron", region: "NA" },
  { name: "Darkspear", slug: "darkspear", region: "NA" },
  { name: "Darrowmere", slug: "darrowmere", region: "NA" },
  { name: "Dath'Remar", slug: "dathremar", region: "NA" },
  { name: "Dawnbringer", slug: "dawnbringer", region: "NA" },
  { name: "Deathwing", slug: "deathwing", region: "NA" },
  { name: "Demon Soul", slug: "demon-soul", region: "NA" },
  { name: "Dentarg", slug: "dentarg", region: "NA" },
  { name: "Destromath", slug: "destromath", region: "NA" },
  { name: "Dethecus", slug: "dethecus", region: "NA" },
  { name: "Detheroc", slug: "detheroc", region: "NA" },
  { name: "Doomhammer", slug: "doomhammer", region: "NA" },
  { name: "Draenor", slug: "draenor", region: "NA" },
  { name: "Dragonblight", slug: "dragonblight", region: "NA" },
  { name: "Dragonmaw", slug: "dragonmaw", region: "NA" },
  { name: "Drak'Tharon", slug: "draktharon", region: "NA" },
  { name: "Drak'thul", slug: "drakthul", region: "NA" },
  { name: "Draka", slug: "draka", region: "NA" },
  { name: "Drakkari", slug: "drakkari", region: "NA" },
  { name: "Dreadmaul", slug: "dreadmaul", region: "NA" },
  { name: "Drenden", slug: "drenden", region: "NA" },
  { name: "Dunemaul", slug: "dunemaul", region: "NA" },
  { name: "Durotan", slug: "durotan", region: "NA" },
  { name: "Duskwood", slug: "duskwood", region: "NA" },
  { name: "Earthen Ring", slug: "earthen-ring", region: "NA" },
  { name: "Echo Isles", slug: "echo-isles", region: "NA" },
  { name: "Eitrigg", slug: "eitrigg", region: "NA" },
  { name: "Eldre'Thalas", slug: "eldrethalas", region: "NA" },
  { name: "Elune", slug: "elune", region: "NA" },
  { name: "Emerald Dream", slug: "emerald-dream", region: "NA" },
  { name: "Eonar", slug: "eonar", region: "NA" },
  { name: "Eredar", slug: "eredar", region: "NA" },
  { name: "Executus", slug: "executus", region: "NA" },
  { name: "Exodar", slug: "exodar", region: "NA" },
  { name: "Farstriders", slug: "farstriders", region: "NA" },
  { name: "Feathermoon", slug: "feathermoon", region: "NA" },
  { name: "Fenris", slug: "fenris", region: "NA" },
  { name: "Firetree", slug: "firetree", region: "NA" },
  { name: "Fizzcrank", slug: "fizzcrank", region: "NA" },
  { name: "Frostmane", slug: "frostmane", region: "NA" },
  { name: "Frostmourne", slug: "frostmourne", region: "NA" },
  { name: "Frostwolf", slug: "frostwolf", region: "NA" },
  { name: "Galakrond", slug: "galakrond", region: "NA" },
  { name: "Gallywix", slug: "gallywix", region: "NA" },
  { name: "Garithos", slug: "garithos", region: "NA" },
  { name: "Garona", slug: "garona", region: "NA" },
  { name: "Garrosh", slug: "garrosh", region: "NA" },
  { name: "Ghostlands", slug: "ghostlands", region: "NA" },
  { name: "Gilneas", slug: "gilneas", region: "NA" },
  { name: "Gnomeregan", slug: "gnomeregan", region: "NA" },
  { name: "Goldrinn", slug: "goldrinn", region: "NA" },
  { name: "Gorefiend", slug: "gorefiend", region: "NA" },
  { name: "Gorgonnash", slug: "gorgonnash", region: "NA" },
  { name: "Greymane", slug: "greymane", region: "NA" },
  { name: "Grizzly Hills", slug: "grizzly-hills", region: "NA" },
  { name: "Gul'dan", slug: "guldan", region: "NA" },
  { name: "Gundrak", slug: "gundrak", region: "NA" },
  { name: "Gurubashi", slug: "gurubashi", region: "NA" },
  { name: "Hakkar", slug: "hakkar", region: "NA" },
  { name: "Haomarush", slug: "haomarush", region: "NA" },
  { name: "Hellscream", slug: "hellscream", region: "NA" },
  { name: "Hydraxis", slug: "hydraxis", region: "NA" },
  { name: "Hyjal", slug: "hyjal", region: "NA" },
  { name: "Icecrown", slug: "icecrown", region: "NA" },
  { name: "Illidan", slug: "illidan", region: "NA" },
  { name: "Jaedenar", slug: "jaedenar", region: "NA" },
  { name: "Jubei'Thos", slug: "jubeithos", region: "NA" },
  { name: "Kael'thas", slug: "kaelthas", region: "NA" },
  { name: "Kalecgos", slug: "kalecgos", region: "NA" },
  { name: "Kargath", slug: "kargath", region: "NA" },
  { name: "Kel'Thuzad", slug: "kelthuzad", region: "NA" },
  { name: "Khadgar", slug: "khadgar", region: "NA" },
  { name: "Khaz Modan", slug: "khaz-modan", region: "NA" },
  { name: "Khaz'goroth", slug: "khazgoroth", region: "NA" },
  { name: "Kil'jaeden", slug: "kiljaeden", region: "NA" },
  { name: "Kilrogg", slug: "kilrogg", region: "NA" },
  { name: "Kirin Tor", slug: "kirin-tor", region: "NA" },
  { name: "Korgath", slug: "korgath", region: "NA" },
  { name: "Korialstrasz", slug: "korialstrasz", region: "NA" },
  { name: "Kul Tiras", slug: "kul-tiras", region: "NA" },
  { name: "Laughing Skull", slug: "laughing-skull", region: "NA" },
  { name: "Lethon", slug: "lethon", region: "NA" },
  { name: "Lightbringer", slug: "lightbringer", region: "NA" },
  { name: "Lightning's Blade", slug: "lightnings-blade", region: "NA" },
  { name: "Lightninghoof", slug: "lightninghoof", region: "NA" },
  { name: "Llane", slug: "llane", region: "NA" },
  { name: "Lothar", slug: "lothar", region: "NA" },
  { name: "Madoran", slug: "madoran", region: "NA" },
  { name: "Maelstrom", slug: "maelstrom", region: "NA" },
  { name: "Magtheridon", slug: "magtheridon", region: "NA" },
  { name: "Maiev", slug: "maiev", region: "NA" },
  { name: "Mal'Ganis", slug: "malganis", region: "NA" },
  { name: "Malfurion", slug: "malfurion", region: "NA" },
  { name: "Malorne", slug: "malorne", region: "NA" },
  { name: "Malygos", slug: "malygos", region: "NA" },
  { name: "Mannoroth", slug: "mannoroth", region: "NA" },
  { name: "Medivh", slug: "medivh", region: "NA" },
  { name: "Misha", slug: "misha", region: "NA" },
  { name: "Mok'Nathal", slug: "moknathal", region: "NA" },
  { name: "Moon Guard", slug: "moon-guard", region: "NA" },
  { name: "Moonrunner", slug: "moonrunner", region: "NA" },
  { name: "Mug'thol", slug: "mugthol", region: "NA" },
  { name: "Muradin", slug: "muradin", region: "NA" },
  { name: "Nagrand", slug: "nagrand", region: "NA" },
  { name: "Nathrezim", slug: "nathrezim", region: "NA" },
  { name: "Nazgrel", slug: "nazgrel", region: "NA" },
  { name: "Nazjatar", slug: "nazjatar", region: "NA" },
  { name: "Nemesis", slug: "nemesis", region: "NA" },
  { name: "Ner'zhul", slug: "nerzhul", region: "NA" },
  { name: "Nesingwary", slug: "nesingwary", region: "NA" },
  { name: "Nordrassil", slug: "nordrassil", region: "NA" },
  { name: "Norgannon", slug: "norgannon", region: "NA" },
  { name: "Onyxia", slug: "onyxia", region: "NA" },
  { name: "Perenolde", slug: "perenolde", region: "NA" },
  { name: "Proudmoore", slug: "proudmoore", region: "NA" },
  { name: "Quel'Thalas", slug: "quelthalas", region: "NA" },
  { name: "Quel'dorei", slug: "queldorei", region: "NA" },
  { name: "Ragnaros", slug: "ragnaros", region: "NA" },
  { name: "Ravencrest", slug: "ravencrest", region: "NA" },
  { name: "Ravenholdt", slug: "ravenholdt", region: "NA" },
  { name: "Rexxar", slug: "rexxar", region: "NA" },
  { name: "Rivendare", slug: "rivendare", region: "NA" },
  { name: "Runetotem", slug: "runetotem", region: "NA" },
  { name: "Sargeras", slug: "sargeras", region: "NA" },
  { name: "Saurfang", slug: "saurfang", region: "NA" },
  { name: "Scarlet Crusade", slug: "scarlet-crusade", region: "NA" },
  { name: "Scilla", slug: "scilla", region: "NA" },
  { name: "Sen'jin", slug: "senjin", region: "NA" },
  { name: "Sentinels", slug: "sentinels", region: "NA" },
  { name: "Shadow Council", slug: "shadow-council", region: "NA" },
  { name: "Shadowmoon", slug: "shadowmoon", region: "NA" },
  { name: "Shadowsong", slug: "shadowsong", region: "NA" },
  { name: "Shandris", slug: "shandris", region: "NA" },
  { name: "Shattered Halls", slug: "shattered-halls", region: "NA" },
  { name: "Shattered Hand", slug: "shattered-hand", region: "NA" },
  { name: "Shu'halo", slug: "shuhalo", region: "NA" },
  { name: "Silver Hand", slug: "silver-hand", region: "NA" },
  { name: "Silvermoon", slug: "silvermoon", region: "NA" },
  { name: "Sisters of Elune", slug: "sisters-of-elune", region: "NA" },
  { name: "Skullcrusher", slug: "skullcrusher", region: "NA" },
  { name: "Skywall", slug: "skywall", region: "NA" },
  { name: "Smolderthorn", slug: "smolderthorn", region: "NA" },
  { name: "Spinebreaker", slug: "spinebreaker", region: "NA" },
  { name: "Spirestone", slug: "spirestone", region: "NA" },
  { name: "Staghelm", slug: "staghelm", region: "NA" },
  { name: "Steamwheedle Cartel", slug: "steamwheedle-cartel", region: "NA" },
  { name: "Stonemaul", slug: "stonemaul", region: "NA" },
  { name: "Stormrage", slug: "stormrage", region: "NA" },
  { name: "Stormreaver", slug: "stormreaver", region: "NA" },
  { name: "Stormscale", slug: "stormscale", region: "NA" },
  { name: "Suramar", slug: "suramar", region: "NA" },
  { name: "Tanaris", slug: "tanaris", region: "NA" },
  { name: "Terenas", slug: "terenas", region: "NA" },
  { name: "Terokkar", slug: "terokkar", region: "NA" },
  { name: "Thaurissan", slug: "thaurissan", region: "NA" },
  { name: "The Forgotten Coast", slug: "the-forgotten-coast", region: "NA" },
  { name: "The Scryers", slug: "the-scryers", region: "NA" },
  { name: "The Underbog", slug: "the-underbog", region: "NA" },
  { name: "The Venture Co", slug: "the-venture-co", region: "NA" },
  { name: "Thorium Brotherhood", slug: "thorium-brotherhood", region: "NA" },
  { name: "Thrall", slug: "thrall", region: "NA" },
  { name: "Thunderhorn", slug: "thunderhorn", region: "NA" },
  { name: "Thunderlord", slug: "thunderlord", region: "NA" },
  { name: "Tichondrius", slug: "tichondrius", region: "NA" },
  { name: "Tol Barad", slug: "tol-barad", region: "NA" },
  { name: "Tortheldrin", slug: "tortheldrin", region: "NA" },
  { name: "Trollbane", slug: "trollbane", region: "NA" },
  { name: "Turalyon", slug: "turalyon", region: "NA" },
  { name: "Twisting Nether", slug: "twisting-nether", region: "NA" },
  { name: "Uldaman", slug: "uldaman", region: "NA" },
  { name: "Uldum", slug: "uldum", region: "NA" },
  { name: "Undermine", slug: "undermine", region: "NA" },
  { name: "Ursin", slug: "ursin", region: "NA" },
  { name: "Uther", slug: "uther", region: "NA" },
  { name: "Vashj", slug: "vashj", region: "NA" },
  { name: "Vek'nilash", slug: "veknilash", region: "NA" },
  { name: "Velen", slug: "velen", region: "NA" },
  { name: "Warsong", slug: "warsong", region: "NA" },
  { name: "Whisperwind", slug: "whisperwind", region: "NA" },
  { name: "Wildhammer", slug: "wildhammer", region: "NA" },
  { name: "Windrunner", slug: "windrunner", region: "NA" },
  { name: "Winterhoof", slug: "winterhoof", region: "NA" },
  { name: "Wyrmrest Accord", slug: "wyrmrest-accord", region: "NA" },
  { name: "Ysera", slug: "ysera", region: "NA" },
  { name: "Ysondre", slug: "ysondre", region: "NA" },
  { name: "Zangarmarsh", slug: "zangarmarsh", region: "NA" },
  { name: "Zul'jin", slug: "zuljin", region: "NA" },
  { name: "Zuluhed", slug: "zuluhed", region: "NA" },
];

// ─── EU (Europe) Realms ─────────────────────────────────────────────────────
export const EU_REALMS: Realm[] = [
  { name: "Aegwynn", slug: "aegwynn", region: "EU" },
  { name: "Aerie Peak", slug: "aerie-peak", region: "EU" },
  { name: "Agamaggan", slug: "agamaggan", region: "EU" },
  { name: "Aggra (Português)", slug: "aggra-portugues", region: "EU" },
  { name: "Aggramar", slug: "aggramar", region: "EU" },
  { name: "Ahn'Qiraj", slug: "ahnqiraj", region: "EU" },
  { name: "Al'Akir", slug: "alakir", region: "EU" },
  { name: "Alexstrasza", slug: "alexstrasza", region: "EU" },
  { name: "Alleria", slug: "alleria", region: "EU" },
  { name: "Alonsus", slug: "alonsus", region: "EU" },
  { name: "Aman'Thul", slug: "amanthul", region: "EU" },
  { name: "Ambossar", slug: "ambossar", region: "EU" },
  { name: "Anachronos", slug: "anachronos", region: "EU" },
  { name: "Anetheron", slug: "anetheron", region: "EU" },
  { name: "Antonidas", slug: "antonidas", region: "EU" },
  { name: "Anub'arak", slug: "anubarak", region: "EU" },
  { name: "Arak-arahm", slug: "arak-arahm", region: "EU" },
  { name: "Arathi", slug: "arathi", region: "EU" },
  { name: "Arathor", slug: "arathor", region: "EU" },
  { name: "Archimonde", slug: "archimonde", region: "EU" },
  { name: "Area 52", slug: "area-52", region: "EU" },
  { name: "Argent Dawn", slug: "argent-dawn", region: "EU" },
  { name: "Arthas", slug: "arthas", region: "EU" },
  { name: "Arygos", slug: "arygos", region: "EU" },
  { name: "Ashenvale", slug: "ashenvale", region: "EU" },
  { name: "Aszune", slug: "aszune", region: "EU" },
  { name: "Auchindoun", slug: "auchindoun", region: "EU" },
  { name: "Azjol-Nerub", slug: "azjol-nerub", region: "EU" },
  { name: "Azshara", slug: "azshara", region: "EU" },
  { name: "Azuregos", slug: "azuregos", region: "EU" },
  { name: "Azuremyst", slug: "azuremyst", region: "EU" },
  { name: "Baelgun", slug: "baelgun", region: "EU" },
  { name: "Balnazzar", slug: "balnazzar", region: "EU" },
  { name: "Blackhand", slug: "blackhand", region: "EU" },
  { name: "Blackmoore", slug: "blackmoore", region: "EU" },
  { name: "Blackrock", slug: "blackrock", region: "EU" },
  { name: "Blackscar", slug: "blackscar", region: "EU" },
  { name: "Blade's Edge", slug: "blades-edge", region: "EU" },
  { name: "Bladefist", slug: "bladefist", region: "EU" },
  { name: "Bloodfeather", slug: "bloodfeather", region: "EU" },
  { name: "Bloodhoof", slug: "bloodhoof", region: "EU" },
  { name: "Bloodscalp", slug: "bloodscalp", region: "EU" },
  { name: "Blutkessel", slug: "blutkessel", region: "EU" },
  { name: "Booty Bay", slug: "booty-bay", region: "EU" },
  { name: "Borean Tundra", slug: "borean-tundra", region: "EU" },
  { name: "Boulderfist", slug: "boulderfist", region: "EU" },
  { name: "Bronze Dragonflight", slug: "bronze-dragonflight", region: "EU" },
  { name: "Bronzebeard", slug: "bronzebeard", region: "EU" },
  { name: "Burning Blade", slug: "burning-blade", region: "EU" },
  { name: "Burning Legion", slug: "burning-legion", region: "EU" },
  { name: "Burning Steppes", slug: "burning-steppes", region: "EU" },
  { name: "C'Thun", slug: "cthun", region: "EU" },
  { name: "Chamber of Aspects", slug: "chamber-of-aspects", region: "EU" },
  { name: "Chants éternels", slug: "chants-eternels", region: "EU" },
  { name: "Cho'gall", slug: "chogall", region: "EU" },
  { name: "Chromaggus", slug: "chromaggus", region: "EU" },
  { name: "Colinas Pardas", slug: "colinas-pardas", region: "EU" },
  { name: "Confrérie du Thorium", slug: "confrerie-du-thorium", region: "EU" },
  { name: "Conseil des Ombres", slug: "conseil-des-ombres", region: "EU" },
  { name: "Crushridge", slug: "crushridge", region: "EU" },
  { name: "Culte de la Rive noire", slug: "culte-de-la-rive-noire", region: "EU" },
  { name: "Daggerspine", slug: "daggerspine", region: "EU" },
  { name: "Dalaran", slug: "dalaran", region: "EU" },
  { name: "Dalvengyr", slug: "dalvengyr", region: "EU" },
  { name: "Darkmoon Faire", slug: "darkmoon-faire", region: "EU" },
  { name: "Darksorrow", slug: "darksorrow", region: "EU" },
  { name: "Darkspear", slug: "darkspear", region: "EU" },
  { name: "Das Konsortium", slug: "das-konsortium", region: "EU" },
  { name: "Das Syndikat", slug: "das-syndikat", region: "EU" },
  { name: "Deathguard", slug: "deathguard", region: "EU" },
  { name: "Deathweaver", slug: "deathweaver", region: "EU" },
  { name: "Deathwing", slug: "deathwing", region: "EU" },
  { name: "Deepholm", slug: "deepholm", region: "EU" },
  { name: "Defias Brotherhood", slug: "defias-brotherhood", region: "EU" },
  { name: "Dentarg", slug: "dentarg", region: "EU" },
  { name: "Der Mithrilorden", slug: "der-mithrilorden", region: "EU" },
  { name: "Der Rat von Dalaran", slug: "der-rat-von-dalaran", region: "EU" },
  { name: "Der abyssische Rat", slug: "der-abyssische-rat", region: "EU" },
  { name: "Destromath", slug: "destromath", region: "EU" },
  { name: "Dethecus", slug: "dethecus", region: "EU" },
  { name: "Die Aldor", slug: "die-aldor", region: "EU" },
  { name: "Die Arguswacht", slug: "die-arguswacht", region: "EU" },
  { name: "Die Nachtwache", slug: "die-nachtwache", region: "EU" },
  { name: "Die Silberne Hand", slug: "die-silberne-hand", region: "EU" },
  { name: "Die Todeskrallen", slug: "die-todeskrallen", region: "EU" },
  { name: "Die ewige Wacht", slug: "die-ewige-wacht", region: "EU" },
  { name: "Doomhammer", slug: "doomhammer", region: "EU" },
  { name: "Draenor", slug: "draenor", region: "EU" },
  { name: "Dragonblight", slug: "dragonblight", region: "EU" },
  { name: "Dragonmaw", slug: "dragonmaw", region: "EU" },
  { name: "Drak'thul", slug: "drakthul", region: "EU" },
  { name: "Drek'Thar", slug: "drekthar", region: "EU" },
  { name: "Dun Modr", slug: "dun-modr", region: "EU" },
  { name: "Dun Morogh", slug: "dun-morogh", region: "EU" },
  { name: "Dunemaul", slug: "dunemaul", region: "EU" },
  { name: "Durotan", slug: "durotan", region: "EU" },
  { name: "Earthen Ring", slug: "earthen-ring", region: "EU" },
  { name: "Echsenkessel", slug: "echsenkessel", region: "EU" },
  { name: "Eitrigg", slug: "eitrigg", region: "EU" },
  { name: "Eldre'Thalas", slug: "eldrethalas", region: "EU" },
  { name: "Elune", slug: "elune", region: "EU" },
  { name: "Emerald Dream", slug: "emerald-dream", region: "EU" },
  { name: "Emeriss", slug: "emeriss", region: "EU" },
  { name: "Eonar", slug: "eonar", region: "EU" },
  { name: "Eredar", slug: "eredar", region: "EU" },
  { name: "Eversong", slug: "eversong", region: "EU" },
  { name: "Executus", slug: "executus", region: "EU" },
  { name: "Exodar", slug: "exodar", region: "EU" },
  { name: "Festung der Stürme", slug: "festung-der-stuerme", region: "EU" },
  { name: "Fordragon", slug: "fordragon", region: "EU" },
  { name: "Forscherliga", slug: "forscherliga", region: "EU" },
  { name: "Frostmane", slug: "frostmane", region: "EU" },
  { name: "Frostmourne", slug: "frostmourne", region: "EU" },
  { name: "Frostwhisper", slug: "frostwhisper", region: "EU" },
  { name: "Frostwolf", slug: "frostwolf", region: "EU" },
  { name: "Galakrond", slug: "galakrond", region: "EU" },
  { name: "Garona", slug: "garona", region: "EU" },
  { name: "Garrosh", slug: "garrosh", region: "EU" },
  { name: "Genjuros", slug: "genjuros", region: "EU" },
  { name: "Ghostlands", slug: "ghostlands", region: "EU" },
  { name: "Gilneas", slug: "gilneas", region: "EU" },
  { name: "Goldrinn", slug: "goldrinn", region: "EU" },
  { name: "Gordunni", slug: "gordunni", region: "EU" },
  { name: "Gorgonnash", slug: "gorgonnash", region: "EU" },
  { name: "Greymane", slug: "greymane", region: "EU" },
  { name: "Grim Batol", slug: "grim-batol", region: "EU" },
  { name: "Grom", slug: "grom", region: "EU" },
  { name: "Gul'dan", slug: "guldan", region: "EU" },
  { name: "Hakkar", slug: "hakkar", region: "EU" },
  { name: "Haomarush", slug: "haomarush", region: "EU" },
  { name: "Hellfire", slug: "hellfire", region: "EU" },
  { name: "Hellscream", slug: "hellscream", region: "EU" },
  { name: "Howling Fjord", slug: "howling-fjord", region: "EU" },
  { name: "Hyjal", slug: "hyjal", region: "EU" },
  { name: "Illidan", slug: "illidan", region: "EU" },
  { name: "Jaedenar", slug: "jaedenar", region: "EU" },
  { name: "Kael'thas", slug: "kaelthas", region: "EU" },
  { name: "Karazhan", slug: "karazhan", region: "EU" },
  { name: "Kargath", slug: "kargath", region: "EU" },
  { name: "Kazzak", slug: "kazzak", region: "EU" },
  { name: "Kel'Thuzad", slug: "kelthuzad", region: "EU" },
  { name: "Khadgar", slug: "khadgar", region: "EU" },
  { name: "Khaz Modan", slug: "khaz-modan", region: "EU" },
  { name: "Khaz'goroth", slug: "khazgoroth", region: "EU" },
  { name: "Kil'jaeden", slug: "kiljaeden", region: "EU" },
  { name: "Kilrogg", slug: "kilrogg", region: "EU" },
  { name: "Kirin Tor", slug: "kirin-tor", region: "EU" },
  { name: "Kor'gall", slug: "korgall", region: "EU" },
  { name: "Krag'jin", slug: "kragjin", region: "EU" },
  { name: "Krasus", slug: "krasus", region: "EU" },
  { name: "Kul Tiras", slug: "kul-tiras", region: "EU" },
  { name: "Kult der Verdammten", slug: "kult-der-verdammten", region: "EU" },
  { name: "La Croisade écarlate", slug: "la-croisade-ecarlate", region: "EU" },
  { name: "Laughing Skull", slug: "laughing-skull", region: "EU" },
  { name: "Les Clairvoyants", slug: "les-clairvoyants", region: "EU" },
  { name: "Les Sentinelles", slug: "les-sentinelles", region: "EU" },
  { name: "Lich King", slug: "lich-king", region: "EU" },
  { name: "Lightbringer", slug: "lightbringer", region: "EU" },
  { name: "Lightning's Blade", slug: "lightnings-blade", region: "EU" },
  { name: "Lordaeron", slug: "lordaeron", region: "EU" },
  { name: "Los Errantes", slug: "los-errantes", region: "EU" },
  { name: "Lothar", slug: "lothar", region: "EU" },
  { name: "Madmortem", slug: "madmortem", region: "EU" },
  { name: "Magtheridon", slug: "magtheridon", region: "EU" },
  { name: "Mal'Ganis", slug: "malganis", region: "EU" },
  { name: "Malfurion", slug: "malfurion", region: "EU" },
  { name: "Malorne", slug: "malorne", region: "EU" },
  { name: "Malygos", slug: "malygos", region: "EU" },
  { name: "Mannoroth", slug: "mannoroth", region: "EU" },
  { name: "Marécage de Zangar", slug: "marecage-de-zangar", region: "EU" },
  { name: "Mazrigos", slug: "mazrigos", region: "EU" },
  { name: "Medivh", slug: "medivh", region: "EU" },
  { name: "Minahonda", slug: "minahonda", region: "EU" },
  { name: "Moonglade", slug: "moonglade", region: "EU" },
  { name: "Mug'thol", slug: "mugthol", region: "EU" },
  { name: "Nagrand", slug: "nagrand", region: "EU" },
  { name: "Nathrezim", slug: "nathrezim", region: "EU" },
  { name: "Naxxramas", slug: "naxxramas", region: "EU" },
  { name: "Nazjatar", slug: "nazjatar", region: "EU" },
  { name: "Nefarian", slug: "nefarian", region: "EU" },
  { name: "Nemesis", slug: "nemesis", region: "EU" },
  { name: "Neptulon", slug: "neptulon", region: "EU" },
  { name: "Ner'zhul", slug: "nerzhul", region: "EU" },
  { name: "Nera'thor", slug: "nerathor", region: "EU" },
  { name: "Nethersturm", slug: "nethersturm", region: "EU" },
  { name: "Nordrassil", slug: "nordrassil", region: "EU" },
  { name: "Norgannon", slug: "norgannon", region: "EU" },
  { name: "Nozdormu", slug: "nozdormu", region: "EU" },
  { name: "Onyxia", slug: "onyxia", region: "EU" },
  { name: "Outland", slug: "outland", region: "EU" },
  { name: "Perenolde", slug: "perenolde", region: "EU" },
  { name: "Pozzo dell'Eternità", slug: "pozzo-delleternita", region: "EU" },
  { name: "Proudmoore", slug: "proudmoore", region: "EU" },
  { name: "Quel'Thalas", slug: "quelthalas", region: "EU" },
  { name: "Ragnaros", slug: "ragnaros", region: "EU" },
  { name: "Rajaxx", slug: "rajaxx", region: "EU" },
  { name: "Rashgarroth", slug: "rashgarroth", region: "EU" },
  { name: "Ravencrest", slug: "ravencrest", region: "EU" },
  { name: "Ravenholdt", slug: "ravenholdt", region: "EU" },
  { name: "Razuvious", slug: "razuvious", region: "EU" },
  { name: "Rexxar", slug: "rexxar", region: "EU" },
  { name: "Runetotem", slug: "runetotem", region: "EU" },
  { name: "Sanguino", slug: "sanguino", region: "EU" },
  { name: "Sargeras", slug: "sargeras", region: "EU" },
  { name: "Saurfang", slug: "saurfang", region: "EU" },
  { name: "Scarshield Legion", slug: "scarshield-legion", region: "EU" },
  { name: "Sen'jin", slug: "senjin", region: "EU" },
  { name: "Shadowsong", slug: "shadowsong", region: "EU" },
  { name: "Shattered Halls", slug: "shattered-halls", region: "EU" },
  { name: "Shattered Hand", slug: "shattered-hand", region: "EU" },
  { name: "Shattrath", slug: "shattrath", region: "EU" },
  { name: "Shen'dralar", slug: "shendralar", region: "EU" },
  { name: "Silvermoon", slug: "silvermoon", region: "EU" },
  { name: "Sinstralis", slug: "sinstralis", region: "EU" },
  { name: "Skullcrusher", slug: "skullcrusher", region: "EU" },
  { name: "Soulflayer", slug: "soulflayer", region: "EU" },
  { name: "Spinebreaker", slug: "spinebreaker", region: "EU" },
  { name: "Sporeggar", slug: "sporeggar", region: "EU" },
  { name: "Steamwheedle Cartel", slug: "steamwheedle-cartel", region: "EU" },
  { name: "Stormrage", slug: "stormrage", region: "EU" },
  { name: "Stormreaver", slug: "stormreaver", region: "EU" },
  { name: "Stormscale", slug: "stormscale", region: "EU" },
  { name: "Sunstrider", slug: "sunstrider", region: "EU" },
  { name: "Suramar", slug: "suramar", region: "EU" },
  { name: "Sylvanas", slug: "sylvanas", region: "EU" },
  { name: "Taerar", slug: "taerar", region: "EU" },
  { name: "Talnivarr", slug: "talnivarr", region: "EU" },
  { name: "Tarren Mill", slug: "tarren-mill", region: "EU" },
  { name: "Teldrassil", slug: "teldrassil", region: "EU" },
  { name: "Temple noir", slug: "temple-noir", region: "EU" },
  { name: "Terenas", slug: "terenas", region: "EU" },
  { name: "Terokkar", slug: "terokkar", region: "EU" },
  { name: "Terrordar", slug: "terrordar", region: "EU" },
  { name: "The Maelstrom", slug: "the-maelstrom", region: "EU" },
  { name: "The Sha'tar", slug: "the-shatar", region: "EU" },
  { name: "The Venture Co", slug: "the-venture-co", region: "EU" },
  { name: "Theradras", slug: "theradras", region: "EU" },
  { name: "Thermaplugg", slug: "thermaplugg", region: "EU" },
  { name: "Thrall", slug: "thrall", region: "EU" },
  { name: "Throk'Feroth", slug: "throkferoth", region: "EU" },
  { name: "Thunderhorn", slug: "thunderhorn", region: "EU" },
  { name: "Tichondrius", slug: "tichondrius", region: "EU" },
  { name: "Tirion", slug: "tirion", region: "EU" },
  { name: "Todeswache", slug: "todeswache", region: "EU" },
  { name: "Trollbane", slug: "trollbane", region: "EU" },
  { name: "Turalyon", slug: "turalyon", region: "EU" },
  { name: "Twilight's Hammer", slug: "twilights-hammer", region: "EU" },
  { name: "Twisting Nether", slug: "twisting-nether", region: "EU" },
  { name: "Tyrande", slug: "tyrande", region: "EU" },
  { name: "Uldaman", slug: "uldaman", region: "EU" },
  { name: "Ulduar", slug: "ulduar", region: "EU" },
  { name: "Uldum", slug: "uldum", region: "EU" },
  { name: "Un'Goro", slug: "ungoro", region: "EU" },
  { name: "Varimathras", slug: "varimathras", region: "EU" },
  { name: "Vashj", slug: "vashj", region: "EU" },
  { name: "Vek'lor", slug: "veklor", region: "EU" },
  { name: "Vek'nilash", slug: "veknilash", region: "EU" },
  { name: "Vol'jin", slug: "voljin", region: "EU" },
  { name: "Wildhammer", slug: "wildhammer", region: "EU" },
  { name: "Wrathbringer", slug: "wrathbringer", region: "EU" },
  { name: "Xavius", slug: "xavius", region: "EU" },
  { name: "Ysera", slug: "ysera", region: "EU" },
  { name: "Ysondre", slug: "ysondre", region: "EU" },
  { name: "Zenedar", slug: "zenedar", region: "EU" },
  { name: "Zirkel des Cenarius", slug: "zirkel-des-cenarius", region: "EU" },
  { name: "Zul'jin", slug: "zuljin", region: "EU" },
  { name: "Zuluhed", slug: "zuluhed", region: "EU" },
];

// ─── Combined ────────────────────────────────────────────────────────────────
export const ALL_REALMS: Realm[] = [...NA_REALMS, ...EU_REALMS];

// ─── Helpers ─────────────────────────────────────────────────────────────────
export function findRealmBySlug(slug: string, region?: "EU" | "NA"): Realm | undefined {
  const list = region === "EU" ? EU_REALMS : region === "NA" ? NA_REALMS : ALL_REALMS;
  return list.find((r) => r.slug === slug);
}

export function findRealmByName(name: string, region?: "EU" | "NA"): Realm | undefined {
  const list = region === "EU" ? EU_REALMS : region === "NA" ? NA_REALMS : ALL_REALMS;
  return list.find((r) => r.name.toLowerCase() === name.toLowerCase());
}

/** Generate a slug from a realm name */
export function realmNameToSlug(name: string): string {
  return name
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "") // strip accents
    .replace(/'/g, "")               // remove apostrophes
    .replace(/[^a-z0-9]+/g, "-")     // non-alphanumeric → hyphen
    .replace(/^-|-$/g, "");          // trim leading/trailing hyphens
}
