-- Initial schema for the crafting project (canonical starting point)

-- Professions: small lookup table
CREATE TABLE professions (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL
);

-- Items: Blizzard-assigned item id is the primary key (not auto-generated)
CREATE TABLE items (
    id bigint PRIMARY KEY,
    name varchar(255) NOT NULL,
    profession_id integer REFERENCES professions(id),
    quality smallint,
    current_price bigint,
    current_price_recorded_at timestamptz
);

-- Recipes
CREATE TABLE recipes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    output_item_id bigint NOT NULL REFERENCES items(id),
    profession_id integer REFERENCES professions(id),
    ingredients_json jsonb,
    output_quantity real NOT NULL DEFAULT 1.0
);

-- Price history for items
CREATE TABLE item_price_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id bigint NOT NULL REFERENCES items(id),
    price bigint NOT NULL,
    recorded_at timestamptz NOT NULL,
    source varchar(255)
);

-- Helpful indexes
CREATE INDEX idx_item_price_history_item_recorded_at ON item_price_history(item_id, recorded_at DESC);

