-- Create item_price_history table for deployments where earlier migrations were applied
-- before this table existed. Uses IF NOT EXISTS to keep this migration idempotent.

CREATE TABLE IF NOT EXISTS item_price_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id bigint NOT NULL REFERENCES items(id),
    price bigint NOT NULL,
    recorded_at timestamptz NOT NULL,
    source varchar(255)
);

CREATE INDEX IF NOT EXISTS idx_item_price_history_item_recorded_at
    ON item_price_history(item_id, recorded_at DESC);
